eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

microservice:
  order-service:
    endpoints:
      endpoint:
        uri: http://customer-service/customer/
